### PR TITLE
CI support refresh to bring in line with Zeek

### PR DESCRIPTION
**Pull request by ckreibich**
Drop Fedora 32, add Fedora 34, add Centos Stream, add OpenSUSE Leaps, add FreeBSD 13

### CODE REVIEW

**Comment by ckreibich** [comment]
I'm hitting some instability here with the checks for Centos 8 and also (in earlier runs) other platforms, but at least so far not with the platform's this PR adds. So I'm moving this out of WIP state, but ... does anybody know what's up with the timeout in the Centos 8 benchmark test?

**Comment by timwoj** [comment]
> does anybody know what's up with the timeout in the Centos 8 benchmark test?

Probably the benchmark host having problems again. I'll look into it today.

**Comment by timwoj** [comment]
I fixed the benchmark host. We changed the port number being used by request from Cirrus, and while I updated the variable the zeek repo, I forgot I had to update it here too. You'll need to rebase your branch on master and then it should build cleanly.

**Review by timwoj — APPROVED** [review]

**Comment by ckreibich** [comment]
Thanks a bunch Tim, will do.

**Pull request merged**
