### PR TITLE
Make Windows CI Dockerfile more like Zeek's

### PR DESCRIPTION
**Pull request by timwoj**
This cleans up the Dockerfile we use for Windows to be more like zeek's, which does things in a cleaner fashion

### CODE REVIEW

**Comment by awelzel** [comment]
Did you see this?
```
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>call git submodule update --recursive --init 
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>if 1 NEQ 0 exit /b 1 
```

**Comment by timwoj** [comment]
Yeah. It needs a little more work.

**Review by ckreibich — APPROVED** [review]

**Comment by Neverlord** [comment]
@timwoj I was about to merge the PR but noticed that it's not targeting the main branch. Did you target the branch `release/2.4` on purpose?

**Comment by timwoj** [comment]
That was where I was seeing it. If it's broken on master too though, I'll merge it there and cherry-pick it over to the release branch.

**Comment by timwoj** [comment]
Merged into master in 3f8f3c774b6714a00cc79ab0db7caca22c002388

**Pull request closed without merging**
