### PR TITLE
Add version negotiation to the handshake process

### PR DESCRIPTION
**Pull request by Neverlord**
Note: This PR forks off from #219 for the new `btest` infrastructure. The first actually new commit is 03ff1ef7b66a7897fb30f17f67171cd77202cf0f.

@rsmmr as discussed last week: this PR adds a new handshake message to Broker for the version negotiation. The handshake now has two distinct phases: the version negotiation with 'fixed' (version-agnostic) message types and the version-dependent peering handshake that currently only exchanges the filters. I have moved all message types to `wire_format.hh` to have all message definitions in one place. There is also a new ping/pong message pair that we use for testing. We could also use them to add heartbeats to Broker later on (and it would work with v1 Broker peers since they already understand the messages).

There are four new btests to validate the handshaking logic in various cases. I hope these are easy to follow.

### CODE REVIEW

**Review by rsmmr — APPROVED** [review]

**Review by rsmmr — COMMENTED** [review]
Couple of issues I'm seeing:

- The unit tests hang for me at `Start 26: python-zeek`. I've rebased the branch to `master` with all the other pending PRs merged; let's see what CI says.
- `btest.cfg` doesn't include the new `handshake` tests. Once I do, those tests fail because of missing baselines.

**Comment by rsmmr** [comment]
> * The unit tests hang for me at `Start 26: python-zeek`.

Nevermind:  I needed to recompile Zeek to pull in the new Broker, working for me now.

But two other tests are failing, @Neverlord please take a look.

> * `btest.cfg` doesn't include the new `handshake` tests. Once I do, those tests fail because of missing baselines.

**Comment by Neverlord** [comment]
The last windows build failed with an assertion, I don't think I've seen that before. I didn't quite get through with that today, but I'm on it.

**Comment by Neverlord** [comment]
@rsmmr that assertion turned out to be another symptom of #228 and wasn't related to the new handshake message. Should be fixed now.

**Comment by rsmmr** [comment]
I see one btest failure still: 

```
[  0%] web-socket.unencrypted ... failed
  % '$SCRIPTS/wait-for-file recv/done 30 || (btest-bg-wait -k 1 && false)' failed unexpectedly (exit code 1)
  % cat .stderr
  <<< [1706] broker-node --config-file=../node.cfg
  "2022-06-01T12:43:50.477" relay: relay messages
  "2022-06-01T12:43:50.765" relay: [<$>/local/data/statuses, (status, endpoint_discovered, (f137acae-71d7-5cc2-8151-3d53908b505d, nil, nil, nil), found a new client in the network)]
  "2022-06-01T12:43:50.765" relay: [<$>/local/data/statuses, (status, peer_added, (f137acae-71d7-5cc2-8151-3d53908b505d, ::1, 60130/tcp, 0), handshake successful)]
  "2022-06-01T12:43:51.878" relay: [<$>/local/data/statuses, (status, endpoint_discovered, (6914d49f-a80b-5559-b81f-ee9e84584a53, nil, nil, nil), found a new client in the network)]
  "2022-06-01T12:43:51.878" relay: [<$>/local/data/statuses, (status, peer_added, (6914d49f-a80b-5559-b81f-ee9e84584a53, ::1, 60131/tcp, 0), handshake successful)]
  "2022-06-01T12:43:51.904" relay: [<$>/local/data/statuses, (status, peer_lost, (6914d49f-a80b-5559-b81f-ee9e84584a53, ::1, 60131/tcp, 0), lost connection to client)]
  "2022-06-01T12:43:51.904" relay: [<$>/local/data/statuses, (status, endpoint_unreachable, (6914d49f-a80b-5559-b81f-ee9e84584a53, nil, nil, nil), lost the last path)]
  >>>
  <<< [1754] python3 ../recv.py >recv.out
  >>>
  <<< [1894] python3 ../send.py
  >>>

1 of 1 test failed
```

Also looks like the btests aren't running on CI? I don't see them in the output.

**Pull request merged**
