### PR TITLE
Fix stalling Broker communication

### PR DESCRIPTION
**Pull request by Neverlord**
Seems like https://github.com/zeek/broker/pull/294 wasn't sufficient to fix what we've seen recently at Corelight. This is the branch we're testing right now, PR is to get CI coverage.

### CODE REVIEW

**Comment by timwoj** [comment]
Looks like this has a merge conflict with the caf submodule. Is that expected? Do you want to move this out of draft status now?

**Comment by Neverlord** [comment]
Looks like our Windows setup broke. 😞

```
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>call ci/windows/build.cmd 

C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>call "c:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 
The system cannot find the path specified.

C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>mkdir build 

C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>cd build 

C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build>C:\WINDOWS\system32\cmd.exe /c C:\Windows\System32\chcp.com 65001   1>NUL  && cmake.exe -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_MAKE_PROGRAM=ninja.exe -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL-Win64" -DEXTRA_FLAGS=/MP8 -DDISABLE_PYTHON_BINDINGS="true" .. 
'cmake.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build>cmake.exe --build . --target install --config release   || exit \b 1 
'cmake.exe' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by timwoj** [comment]
Ok. `master` should be fixed now if you want to rebase this again.

**Review by timwoj — APPROVED** [review]

**Comment by grigorescu** [comment]
> fix what we've seen recently at Corelight.

@Neverlord Can you share a few more details as to what exactly you saw? I've also been working on debugging a stall under certain conditions, and I can't tell if this issue is about that or something else.

**Comment by Neverlord** [comment]
The stall seemed to happen only with many workers (>90) and high traffic (80Gbps IIRC). I couldn't reproduce it locally, so I can't actually give you some guidance on how to reproduce it reliably. The script they've used killed workers and paused/unpaused worker processes. So it's some combination of these factors.

The end result on the Broker side, however, was that Broker stopped processing any inputs and everything Zeek tries to send just gets buffered (i.e., memory usage goes up over time).

**Comment by grigorescu** [comment]
Interesting, thanks. We're seeing a stall with many workers, but almost no traffic.

**Comment by awelzel** [comment]
@grigorescu - interesting (and scary). Are you still seeing/reproducing it with 5.0.4/5.1.1 ?

**Pull request merged**
